Repository skytap/well-architected-framework, pull requests merged in 2023-02, with the labels that each got.

#190 Review and Merge of February2023 links review dev branch
  _config.yml
  _layouts/page.html
  index.md
  operations/Discovery/README.md
  operations/Discovery/discoveryecosystems.md
  operations/Discovery/discoveryworkloads.md
  operations/README.md
  operations/connectivity/ExpressRoute/skytap2azureexpressroute.md
  operations/connectivity/README.md
  operations/connectivity/skytaponazureconnectivity.md
  operations/connectivity/skytaponibmconnectivity.md
  operations/ecosystems/README.md
  operations/ecosystems/azurenative/solutions/AzureNetAppFiles/Skytap+AzureNetAppFiles.md
  operations/ecosystems/azurenative/solutions/SAP/README.md
  resiliency/README.md
  resiliency/backups.md
  resiliency/designconsiderationsazure.md
  resiliency/designconsiderationsibm.md
  resiliency/disasterrecovery.md
  resiliency/hadr.md
  resiliency/migrations.md
  resiliency/solutions/BRMS/ibmiworkloadmigration.md
  resiliency/solutions/ColdMigrationsOverview.md
  resiliency/solutions/GoSave/ibmimigrationwithgosave.md
  resiliency/solutions/GoSave/ibmimigrationwithgosaveupdate2022.md
  resiliency/solutions/HotMigrationOverview.md
  resiliency/solutions/IMBiLPARMigrationWithPowerVC.md
  resiliency/solutions/PowerHAGeoMirror.md
  resiliency/solutions/SkytapCommvaultRunbook.md
  resiliency/solutions/VTL/IBMi-iSCSI-VTL-Backups.md
  resiliency/solutions/databoxmigrations.md
  resiliency/solutions/liveclone.md
  resiliency/solutions/mksysb-backupandrestore.md
  resiliency/solutions/savetemplatecopy2region/savetemplatecopy2region.md
  security/README.md
  security/edgenetworking.md
  security/internalnetworking.md
  security/keysecurityareas.md
  security/securityasaservice.md
  security/securitymanagement.md
  security/virtualmachines.md
Labels: bug, documentation, help wanted

#215 Review and merge - Updated February2023 links review dev branch 02
  .vs/VSWorkspaceState.json
  .vs/WAF/v16/.suo
  .vs/slnx.sqlite
  operations/connectivity/ExpressRoute/skytap2azureexpressroute.md
  resiliency/solutions/IMBiLPARMigrationWithPowerVC.md
Labels: bug

#216 Fixed external link in virtualmachines.md per #213
  .vs/VSWorkspaceState.json
  .vs/WAF/v16/.suo
  .vs/slnx.sqlite
  security/virtualmachines.md
Labels: bug

#217 hadr.md permalink changed to /resiliency/high-availability/ per #214
  _layouts/page.html
  operations/Discovery/discoveryworkloads.md
  resiliency/README.md
  resiliency/backups.md
  resiliency/designconsiderationsazure.md
  resiliency/designconsiderationsibm.md
  resiliency/disasterrecovery.md
  resiliency/hadr.md
  resiliency/migrations.md
  resiliency/solutions/BRMS/ibmiworkloadmigration.md
  resiliency/solutions/ColdMigrationsOverview.md
  resiliency/solutions/GoSave/ibmimigrationwithgosave.md
  resiliency/solutions/GoSave/ibmimigrationwithgosaveupdate2022.md
  resiliency/solutions/HotMigrationOverview.md
  resiliency/solutions/IMBiLPARMigrationWithPowerVC.md
  resiliency/solutions/PowerHAGeoMirror.md
  resiliency/solutions/SkytapCommvaultRunbook.md
  resiliency/solutions/VTL/IBMi-iSCSI-VTL-Backups.md
  resiliency/solutions/databoxmigrations.md
  resiliency/solutions/liveclone.md
  resiliency/solutions/mksysb-backupandrestore.md
  resiliency/solutions/savetemplatecopy2region/savetemplatecopy2region.md
Labels: enhancement

#221 resolve typo in skytaponazureconnectivity.md
  .vs/VSWorkspaceState.json
  .vs/WAF/v16/.suo
  .vs/slnx.sqlite
  operations/connectivity/skytaponazureconnectivity.md
Labels: documentation, good first issue
